### ISSUE TITLE
Solved! @esx_shops/server/main.lua:37: attempt to mul a 'string' with a 'number'

### ISSUE THREAD

**Issue by Obektev** [esx-framework/esx_shops#13]
1. Go to esx_shops/server/main.lua
2. Open it with any text editor
3. find 16 line `return item.price, item.label`
4. change it to `return true, item.price, item.label`
5. save file and restart esx_shops

**Comment by Gellipapa** [comment]
@Obektev Thank you for report backwards issue. I fixed #14
