### ISSUE TITLE
[Bug] first time you enter the marker

### ISSUE THREAD

**Issue by NexDK** [esx-framework/esx_shops#19]
**First time you enter the marker the text just say "ESX-TextUI"**
![Skærmbillede 2023-09-25 153621](https://github.com/esx-framework/esx_shops/assets/36231983/450fb316-9efc-4b04-8ba4-165d4bbfd968)

**after the 1 time the shop has been open it works**

![Skærmbillede 2023-09-25 153636](https://github.com/esx-framework/esx_shops/assets/36231983/e812544b-0db4-424d-857d-e0367799ff61)

**Comment by Arctos2win** [comment]
Hi @NexDK, 

thanks for reporting this, i resolved the problem. 
you can just redownload esx_shops from github and it should work.

**Comment by NexDK** [comment]
That was fast, thank you :-)
