### ISSUE TITLE
SCRIPT ERROR: @esx_shops/client/main.lua:15: attempt to index a nil value (field '?')

### ISSUE THREAD

**Issue by TehZombiJesus** [esx-framework/esx_shops#88]
I just updated all the plugins and I'm getting this error.

-- > https://imgur.com/0vuJMLJ

**Comment by TehZombiJesus** [comment]
I also found an error when I try to buy something it opens the menu but I see no items and gives this error;

-- > `script:esx_menu_default:nui` `Uncaught TypeError: Cannot read property 'scrollIntoView' of undefined (@esx_menu_default/html/js/app.js:67)`

**Comment by gabrielcalderon** [comment]
Same issue here... I was not having this issue, it started happening randomly.

**Comment by krymnon** [comment]
Same issue here. Any news or progress?

**Comment by gabrielcalderon** [comment]
@krymnon I solved my issue by adding Water and Bread into the "items" table of the Database.

```
INSERT INTO `items` (`name`, `label`, `weight`) VALUES
	('bread', 'Bread', 1),
	('water', 'Water', 1)
;
```

**Comment by krymnon** [comment]
I found the culprit, it was linked to esx_extraitems

I just installed the bundled .sql file from esx_extraitems without editing it first, 
so it installed all items to a non-existing shop.
